name: dart2ts
author: Vittorio Ballestra <vittorio.ballestra@gmail.com>
homepage: https://github.com/orgs/polymer-dart
description: A better interface for TS
version: 0.0.1
dependencies:
  build: ^0.10.0
  build_runner: any
  analyzer: ^0.30.0
  args: any
  source_gen: any
executables:
 dart2ts: dart2ts
environment:
    sdk: ">=1.8.0 <2.0.0"
